apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: observability-operatorgroup
  namespace: NAMESPACE
spec:
  targetNamespaces:
   - NAMESPACE
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: NAMESPACE
  labels:
    operators.coreos.com/grafana-operator.observability: ""
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v4.6.0
